import numpy as np 
import nltk
import re
from Cipher import Cipher
# from Cipher import FuerzaBruta, EfuerzaBruta, DfuerzaBruta

alphabetS = 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'
mensajeCesar = 'Esto es apenas un texto de prueba.'
mensajeAfin = 'Hola Mundo Soy un Hacker!'
mensajeVigenere = 'Esta es La Prueba del Cifrado Vige!'
probabilidad_teorica = {'A': 0.1253, 'B': 0.0142, 'C': 0.0468, 'D': 0.0586, 'E': 0.1368, 'F': 0.0069, 'G': 0.0101, 'H': 0.007, 'I': 0.0625, 'J': 0.0044, 'K': 0.0002, 'L': 0.0497, 'M': 0.0315, 'N': 0.0671, 'Ñ': 0.0031, 'O': 0.0868, 'P': 0.0251, 'Q': 0.0088, 'R':0.0687, 'S':0.0798, 'T':0.0463, 'U': 0.0393, 'V': 0.009, 'W': 0.0001, 'X': 0.0022, 'Y': 0.009, 'Z': 0.0052}
cipher = Cipher(alphabetS, probabilidad_teorica)
llave_cesar = 10
llave_afin = [5, 12]
llave_vig = 'palabra'

d3 = cipher.Dvigenere('bees', 'DYEFESJKBCFSSXSDPPISSVERPOELFWMFUMSIFVHAESEUFTXHRYIQBQEVBTSVSMELBOZSSOSDBWIDWETHEIVHTEHWHYEMFPEDBOSZBFMSBTVWTEHHJPTDBGETMICVFJMFJXMÑBEQMFWYAHQSKBQGABXSIPKVSGMGSTIWWÑXSUPQXKBQUNJOMVBHEWTTIKBVOSNYIKUIUNJWSEPVMKBOOATMQFJQKNÑEILQIVSÑDESJWOSESGHÑIOIFQWSNMIFUSJAKSIFMEILQERSEMWMBQXWQEVMJGYDBVPWÑXIWÑIOUPQZWÑXSVFOSLBFVHKSWVPQHWDEVDPWUNJQXHDSQVFWGWÑHMWSEYFBZIRBFEBBVHWTYIEJQIFDMEIBVEVFGMKMIUNFGSFGMETBIQWMGIDPVIDJKMHTSHWTYOSCSVKFHIFUSVSBOHWTTIKUEVLFIQUPQXKPVSVFEHHQSVNÑKVNQSHWJQHAHIQSTHIKPWXKPMPIBWMTMIUNFWIVJWTHÑMEFBWEUSMJADEVDPEQMFYQSMXEKVQEDUEVJVIETBVXHMSPWMITSSIGAPGSEPIODFGLHFQUNFHILDEQLBVMSBOJAÑHILVWXWNSVWTHILVHILUMQHEIWANMWEPXVWTERHTIQWMTEATOIZBFMSÑGSFGIVAESYFNIHABQSVPPMFJSHWMEWDFQKNBWQSUMZSTMQMFQXHBOKHEMNHBOKNÑEWIBOETSEWJVIJNFVSFDSPISIQVJHELFQXHÑGILGOSKFGMHFQIDVQEAEIEJVIXNWSTHSHMYÑEHWTYXSMIQMPCHWTYGNMXYKBYQAWIVLBOCVFWYSSHYHDSQHDMPAFQXHEIEKJWXHUIOWTVIUPVHHRYIIBVEWTIHABWIWTTIKBFENÑIGDJTWWUSXSMHILPOCVJWTNTSIFMSPSTMQMJPSÑBOIKTIHWBUYWMGSFPGMEJIQMPTEKBIQYBREKBWYLPTVWTSVWTCWSMZEKMEZAEEWANIPSUEMLMIWVJNSIVIHHIEGWSUYWFOWHMWIHTGYKFDGSFQWNBOXNSEOHTMQVJKIFBWOHNMVSSSQXJNEEFQXWZFEKUSOHNIWHSTVWÑHMHMEMFDVIVVOMVBHIFTYWHKSWÑJSUNFWIISSHNKSYFQIUNFRSUPQWWKSCWTTIKPGSFGMEVPQSLJQGAFVXHEIWVFQHHTLSKBWHWTTYWTIOUPVERPQHWGVEQCEVMPOSEFEVKBDSDBGLHSVISCEWNTEQYSIZWIIPWÑXILPFVWMETAFHVSEIOHTWEUSMJADMSLCVMDMEQMFFEBPOEHQEGSMYDVFYQLPOIUMMTLBHSEJIQMSEWNÑSHWMSWAÑHMYFQELSIGAUEFSTMQFJQKNÑEMFGOIPJSQVFZSRTMQISMWSVQEIPVYFBOELJQJAÑMXSTJIUIEWWÑUYWTITKPHYUJVMSÑIGDJTWWTWSDBVILZOYFBVILRYIDPWELUVSFPPSLEIOSDSPNÑMHSEPEQBLETJEQISIZATXSQBQSMBHSWÑWYLDSHADIWLJQOSWEOAPWESZYHSEIEKJWXHUIOWT')
print('Desencriptacion cifrado vigenere: \n',d3,'\n')